baseURL = "https://serene-minsky-5f868d.netlify.com/"
languageCode = "nl-nl"
title = "In Between"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = true
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /nl/. The root directory / will redirect to /nl/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "nl"

# Site Params
[params]
    logo = "images/logo.png"

    # Choice of languages: NL / EN
    [[Params.listeLangues]]
    code = "nl"
    [[Params.listeLangues]]
    code = "en"

# Choice of languages: NL / EN
[Languages]
    ############ 1 - Site in Nederlands
    [Languages.nl]
    weight = 1
    languageCode = "nl-nl"
    title = "In Between"
    dateFormat = "2 January 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "Nederlandse beschrijving."
    footerServiceTitle = "Nederlands links 1"
    footerQuicklinkTitle = "Nederlands links 2"
    footerAboutTitle = "Nederlandse beschrijving titel"
    footerSubscribeTitle = "Abonneer je op de nieuwsbrief"

    # Slider Section
    [Languages.nl.params.slider]
        enable = true
        title = "Creating places of humanity"
        subtitle = "is de uitnodiging mee te doen aan het leefbaar maken van plaatsen waar mensen samenkomen, wonen, samen optrekken. Compassie die verbindt gestalte geven in nieuwe vormen van communitair leven."
        bgImage = "images/wooden-bridge-medium.jpg"
        btnText = "Lees meer"
        url = "nl/about"

    # Hero Area Section
    [Languages.nl.params.hero]
        enable  = true
        heading = "FRANCAIS We love to make brands grow"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = true
        btnText = "Know More"
        btnURL  = "https://themefisher.com/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [Languages.nl.params.aboutSm]
        enable  = true
        title   = "Tussenruimte voor ontmoeten, samen leven en samen leren."
        description = "Verbinding tussen mensen, groepen en organisaties met oog op medemenselijkheid, compassie. Mensen in verschillende werkkringen en contexten ontmoeten elkaar in initiatief dat context overstijgt, bouwen bruggen die tot nieuwe stappen leiden."

    # Blog Section On Homepage
    [Languages.nl.params.blog]
        enable  = true
        topTitle= "Zien en gezien worden."
        title   = "in-between blog"
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.nl.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "FRANCAIS Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.nl.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "FRANCAIS Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Nous contacter"

    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "ENGLISH Example site multi-language"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "ENGLISH Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "ENGLISH Service"
    footerQuicklinkTitle = "ENGLISH Quicklinks"
    footerAboutTitle = "ENGLISH About"
    footerSubscribeTitle = "ENGLISH Subscribe"

    #  Slider Section
    [Languages.en.params.slider]
    enable = true
    title = "Creating places of humanity"
    subtitle = "is de uitnodiging mee te doen aan het leefbaar maken van plaatsen waar mensen samenkomen, wonen, samen optrekken. Compassie die verbindt gestalte geven in nieuwe vormen van communitair leven."
    bgImage = "images/wooden-bridge-medium.jpg"
    btnText = "Keep reading"
    url = "en/about"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "ENGLISH We love to make brands grow"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
        button  = true
        btnText = "Know More"
        btnURL  = "https://themefisher.com/"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "Space to live and learn together."
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "See and be seen."
        title   = "in-between blog"
        subtitle= "Unfortunately, at this time the blog is only in Dutch."

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "ENGLISH Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "ENGLISH Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
